### PR TITLE
Userenv

### PR DESCRIPTION
**Pull request by atheurer**
updated to better support compiling tools

### CODE REVIEW

**Review by k-rister — COMMENTED** [review]
Shouldn't you regenerate all the userenvs that use these components?

**Comment by atheurer** [comment]
> Shouldn't you regenerate all the userenvs that use these components?

Unfortunately it's not super obvious which userenvs use a specific component.  I am trying to build all userenvs, but I am seeing one error, probably another missing file:

```
$ ./build.sh rhubi9
~/repos/crucible/subprojects/core/rickshaw/userenvs/rhubi9 ~/repos/crucible/subprojects/core/rickshaw/userenvs
~/repos/crucible/subprojects/core/rickshaw/userenvs/rhubi9/requirements ~/repos/crucible/subprojects/core/rickshaw/userenvs/rhubi9 ~/repos/crucible/subprojects/core/rickshaw/userenvs
found 01-alma9-repos.json
cat: 01-alma9-repos.json: No such file or directory
found 02-python.json
found 03-core-utils.json
found 04-core-compiling.json
found 05-numa-utils.json
found 06-core-perl.json
found 07-core-node.json
~/repos/crucible/subprojects/core/rickshaw/userenvs/rhubi9 ~/repos/crucible/subprojects/core/rickshaw/userenvs
~/repos/crucible/subprojects/core/rickshaw/userenvs
parse error: Expected value before ',' at line 30, column 1
```

**Comment by k-rister** [comment]
Ugh, yes, I missed another one...I'm fixing it.

**Comment by k-rister** [comment]
#468

**Review by k-rister — COMMENTED** [review]
Did you forget to add `rpm-core-compiling-older.json`?

**Comment by atheurer** [comment]
> Did you forget to add `rpm-core-compiling-older.json`?

Yes.  Added now.

**Review by k-rister — APPROVED** [review]

**Pull request merged**
