### PR TITLE
restore deprecated properties to run.json schema

### PR DESCRIPTION
**Pull request by k-rister**
- even though these properties are no longer used they ar necessary for processing/indexing existing data

### CODE REVIEW

**Comment by k-rister** [comment]
@HughNhan Can you confirm that this patch fixes your indexing problem?

**Comment by k-rister** [comment]
Assuming that this passes CI (I just had to make a typo bugfix), if @HughNhan says it's good for him then the `DO NOT MERGE` label no longer applies.

**Comment by HughNhan** [comment]
It works. I can index the problematic run that the previous attempt before the fix would error out.

**Review by HughNhan — APPROVED** [review]
LGTM. Work great for me (WGFM)

**Pull request merged**
