### PR TITLE
Add multibench support to all-in-one json

### PR DESCRIPTION
**Pull request by rafaelfolco**
Add benchmarks block to identify bench ids

### CODE REVIEW

**Comment by rafaelfolco** [comment]
Depends-On: https://github.com/perftool-incubator/bench-fio/pull/50

**Comment by rafaelfolco** [comment]
@k-rister Looks like the self-hosted jobs are failing. Could you pls take a look ?

**Comment by k-rister** [comment]
> @k-rister Looks like the self-hosted jobs are failing. Could you pls take a look ?

I took a quick look and don't see anything obviously wrong.  Can you try running it again?  A bunch of jobs ran successfully yesterday so whatever was broken may already be resolved.

**Comment by rafaelfolco** [comment]
> > @k-rister Looks like the self-hosted jobs are failing. Could you pls take a look ?
> 
> I took a quick look and don't see anything obviously wrong. Can you try running it again? A bunch of jobs ran successfully yesterday so whatever was broken may already be resolved.

```
  Error: error: insufficient permission for adding an object to repository database .git/objects
  Error: fatal: failed to write object
  Error: fatal: unpack-objects failed
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by rafaelfolco** [comment]
> > > @k-rister Looks like the self-hosted jobs are failing. Could you pls take a look ?
> > 
> > 
> > I took a quick look and don't see anything obviously wrong. Can you try running it again? A bunch of jobs ran successfully yesterday so whatever was broken may already be resolved.
> 
> ```
>   Error: error: insufficient permission for adding an object to repository database .git/objects
>   Error: fatal: failed to write object
>   Error: fatal: unpack-objects failed
>   Error: The process '/usr/bin/git' failed with exit code 128
> ```
Tried this but it doesn't seem to help :(
https://stackoverflow.com/questions/6448242/git-push-error-insufficient-permission-for-adding-an-object-to-repository-datab

**Pull request closed without merging**
